name: bitcoin_jsonrpc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  pedantic: ^1.11.1
  crypto:
  hash:
    git: https://github.com/redDwarf03/hash
  ninja: ^3.0.2
  ninja_bip32:
    path: ../ninja_bip32
  bs58check: ^1.0.2
  bech32: ^0.2.1
  ninja_basex: ^1.0.1

dev_dependencies:
  test: ^1.17.10
